[package]
name = "frp"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
futures-signals = "0.3.34"
pin-project = "1.1.8"
tokio = { version = "1.43.0", features = ["rt"] }
tokio-stream = "0.1.17"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt", "macros"] }
